# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

binomial_mixture_log_likelihood <- function(x, n, p1, p2, theta1) {
    .Call('_scMitoMut_binomial_mixture_log_likelihood', PACKAGE = 'scMitoMut', x, n, p1, p2, theta1)
}

binomial_log_likelihood <- function(x, n, p) {
    .Call('_scMitoMut_binomial_log_likelihood', PACKAGE = 'scMitoMut', x, n, p)
}

em_bm <- function(x, n, p1 = 0.5, p2 = 0.6, theta1 = 0.7, max_iter = 1000L, tol = 0.001) {
    .Call('_scMitoMut_em_bm', PACKAGE = 'scMitoMut', x, n, p1, p2, theta1, max_iter, tol)
}

log_n_choose_k <- function(n, k) {
    .Call('_scMitoMut_log_n_choose_k', PACKAGE = 'scMitoMut', n, k)
}

log_beta_binomial_pmf <- function(a, b, x, n) {
    .Call('_scMitoMut_log_beta_binomial_pmf', PACKAGE = 'scMitoMut', a, b, x, n)
}

pbetabinom <- function(x, n, a, b) {
    .Call('_scMitoMut_pbetabinom', PACKAGE = 'scMitoMut', x, n, a, b)
}

mle_bb <- function(x, n, max_iter = 100L, tol = 1e-3) {
    .Call('_scMitoMut_mle_bb', PACKAGE = 'scMitoMut', x, n, max_iter, tol)
}

